add langchain example
OriginTrail/ChatDKG pull request #1
Opened 2023-07-14 15:04 UTC by zeroxbt

2023-07-14 16:13 UTC, branarakic requested changes

2023-07-14 16:13 UTC, branarakic commented on examples/langchain/dkg-demo.js
> +const yewmakerol = JSON.parse(fs.readFileSync("./yewmakerol.json"));
let's add some inline comments to explain what is happening here (why yewmakerol.json)
would also be good to point to a demo video from the comments

2023-07-14 16:13 UTC, branarakic commented on examples/langchain/generate-tsv.js
> +
Also would add some explanatory comments here

2023-07-14 16:13 UTC, branarakic commented on examples/langchain/search.py
> +
Some basic comments would provide an easier way to navigate and understand the code a well

2023-07-14 16:13 UTC, branarakic commented on examples/langchain/README.md
> +This example walks you through the process of creating a knowledge asset on the Origintrail decentralized knowledge graph and searching the knowledge asset using the power of Langchain and OpenAI.
Let's provide some more context in the readme: what are KAs, reference Milvus, explain in a few steps what the algo looks like, include links where appropriate, including the video where we showed this demo (ideally at the point of showing it)

2023-07-18 10:56 UTC, NZT48 requested changes

2023-07-18 10:56 UTC, NZT48 commented on examples/langchain/README.md
> +cd ChatDKG
```suggestion
cd ChatDKG/examples/langchain
```

2023-07-18 10:56 UTC, NZT48 commented on examples/langchain/dkg-demo.js
> +    name: "otp::testnet",
I would put into readme link to our discord link and say that they can get tokens from our faucet on discord

2023-07-18 10:56 UTC, NZT48 commented on examples/langchain/README.md
> +
Should we add also OpenAi API key as prerequisite

2023-07-18 13:20 UTC, branarakic commented on examples/langchain/README.md
> +
It's optional, but should be indicated

2023-07-21 15:51 UTC, merged